### ISSUE TITLE
New IA: Fill in documentation 

### ISSUE THREAD

**Issue by alhambrav** [craftersoftware/craftercms#5214]
Fill in/update the following documentation for the following files:

##### Tasks
- [ ] (Sumer) [by-role/architect/deployment-architecture.rst](https://github.com/craftercms/docs/blob/master/source/.new-ia/by-role/architect/deployment-architecture.rst)
- [x] (Sumer) [by-role/architect/availability.rst](https://github.com/craftercms/docs/blob/master/source/new-ia/by-role/architect/availablility.rst)
- [ ] (Sumer) [by-role/architect/general-architecture.rst](https://github.com/craftercms/docs/blob/master/source/new-ia/by-role/architect/general-architecture.rst)
- [x] (Sumer) [by-role/architect/headless.rst](https://github.com/craftercms/docs/blob/master/source/new-ia/by-role/architect/headless.rst)
- [x] (Sumer) [by-role/architect/scalability.rst](https://github.com/craftercms/docs/blob/master/source/new-ia/by-role/architect/scalability.rst)
- [x] (Sumer) [by-role/architect/security.rst](https://github.com/craftercms/docs/blob/master/source/new-ia/by-role/architect/security.rst)
- [x] (Sumer) [by-role/architect/templated.rst](https://github.com/craftercms/docs/blob/master/source/new-ia/by-role/architect/templated.rst)
- [ ] (Sumer) [index.rst](https://github.com/craftercms/docs/blob/master/source/new-ia/index.rst)
- [x] (Sumer) [roadmap/index.rst](https://github.com/craftercms/docs/blob/master/source/new-ia/roadmap/index.rst)
- [ ] (Sumer) [by-role/system-admin/deployment-architecture.rst](https://github.com/craftercms/docs/blob/master/source/new-ia/by-role/system-admin/deployment-architecture.rst)
- [ ] (Sumer) [by-role/system-admin/disaster-recovery.rst](https://github.com/craftercms/docs/blob/master/source/new-ia/by-role/system-admin/disaster-recovery.rst)
- [ ] (Sumer) [by-role/system-admin/performance-and-scaling.rst](https://github.com/craftercms/docs/blob/master/source/new-ia/by-role/system-admin/performance-and-scaling.rst)
- [ ] (Vita) [by-role/developer/headless/security.rst](https://github.com/craftercms/docs/blob/master/source/new-ia/by-role/developer/headless/security.rst)
- [ ] (Vita) [by-role/developer/headless/examples/mobile.rst](https://github.com/craftercms/docs/tree/master/source/new-ia/by-role/developer/headless/examples/mobile.rst)
- [ ] (Vita) [by-role/developer/headless/examples/other-spa.rst](https://github.com/craftercms/docs/tree/master/source/new-ia/by-role/developer/headless/examples/other-spa.rst)
- [ ] (Vita) [by-role/developer/headless/examples/react-spa.rst](https://github.com/craftercms/docs/tree/master/source/new-ia/by-role/developer/headless/examples/react-spa.rst)
- [ ] (Vita) [by-role/developer/templated/examples/blogs.rst](https://github.com/craftercms/docs/blob/master/source/new-ia/by-role/developer/templated/examples/blogs.rst)
- [ ] (Vita) [by-role/developer/templated/examples/microsites-and-landing-pages.rst](https://github.com/craftercms/docs/blob/master/source/new-ia/by-role/developer/templated/examples/microsites-and-landing-pages.rst)
- [ ] (Vita) [by-role/developer/templated/examples/saml2-intranet.rst](https://github.com/craftercms/docs/blob/master/source/new-ia/by-role/developer/templated/examples/saml2-intranet.rst)
- [ ] (Vita) [by-role/developer/templated/security.rst](https://github.com/craftercms/docs/blob/master/source/new-ia/by-role/developer/templated/security.rst)
- [ ] (Vita) [by-role/developer/templated/groovy-controllers.rst](https://github.com/craftercms/docs/blob/master/source/new-ia/by-role/developer/templated/groovy-controllers.rst)

Articles that needs a new home / updates in the new-ia
- [x] [cook-books/active-cache/cache-a-restful-response.rst](https://github.com/craftercms/docs/blob/master/source/developers/cook-books/active-cache/cache-a-restful-response.rst)
- [x] [cook-books/activiti/start-a-process.rst](https://github.com/craftercms/docs/blob/master/source/developers/cook-books/activiti/start-a-process.rst)
- [ ] [cook-books/best-practices/best-practice-loading-content.rst](https://github.com/craftercms/docs/blob/master/source/developers/cook-books/best-practices/best-practice-loading-content.rst)
- [x] [cook-books/how-tos/change-log-data-folder-location.rst](https://github.com/craftercms/docs/blob/master/source/developers/cook-books/how-tos/change-log-data-folder-location.rst)
- [ ] [cook-books/how-tos/integrating-crafter-cms-with-bitbucket.rst](https://github.com/craftercms/docs/blob/master/source/developers/cook-books/how-tos/integrating-crafter-cms-with-bitbucket.rst)
- [ ] [cook-books/how-tos/integrating-crafter-cms-with-cloud.rst](https://github.com/craftercms/docs/blob/master/source/developers/cook-books/how-tos/integrating-crafter-cms-with-cloud.rst)
- [ ] [cook-books/how-tos/integrating-crafter-cms-with-github.rst](https://github.com/craftercms/docs/blob/master/source/developers/cook-books/how-tos/integrating-crafter-cms-with-github.rst)
- [ ] [cook-books/how-tos/integrating-crafter-cms-with-gitlab.rst](https://github.com/craftercms/docs/blob/master/source/developers/cook-books/how-tos/integrating-crafter-cms-with-gitlab.rst)
- [ ] [cook-books/how-tos/setting-up-an-ldap-server-for-dev.rst](https://github.com/craftercms/docs/blob/master/source/developers/cook-books/how-tos/setting-up-an-ldap-server-for-dev.rst)
- [ ] [cook-books/how-tos/using-custom-processors-with-crafter-deployer.rst](https://github.com/craftercms/docs/blob/master/source/developers/cook-books/how-tos/using-custom-processors-with-crafter-deployer.rst)
- [ ] [cook-books/how-tos/web-app-manifest-use-credentials.rst](https://github.com/craftercms/docs/blob/master/source/developers/cook-books/how-tos/web-app-manifest-use-credentials.rst)
- [x] [cook-books/rte/inserting-links-to-pages-in-the-rte.rst](https://github.com/craftercms/docs/blob/master/source/developers/cook-books/rte/inserting-links-to-pages-in-the-rte.rst)
- [x] [cook-books/services/get-a-list-of-sites.rst](https://github.com/craftercms/docs/blob/master/source/developers/cook-books/services/get-a-list-of-sites.rst)
- [x] [cook-books/services/get-site-pages.rst](https://github.com/craftercms/docs/blob/master/source/developers/cook-books/services/get-site-pages.rst)
- [x] [cook-books/services/rendered-components-as-json.rst](https://github.com/craftercms/docs/blob/master/source/developers/cook-books/services/rendered-components-as-json.rst)
- [ ] [by-role/developer/developer-workflow/code-repo-n-devcontentops-workflow.rst](https://github.com/craftercms/docs/blob/master/source/new-ia/by-role/developer/developer-workflow/code-repo-n-devcontentops-workflow.rst)
- [ ] [by-role/developer/developer-workflow/connecting-prod-cms-to-dev-workflow.rst](https://github.com/craftercms/docs/blob/master/source/new-ia/by-role/developer/developer-workflow/connecting-prod-cms-to-dev-workflow.rst)
- [ ] [by-role/developer/developer-workflow/developer-workflow.rst](https://github.com/craftercms/docs/blob/master/source/new-ia/by-role/developer/developer-workflow/developer-workflow.rst)
- [ ] [by-role/developer/developer-workflow/implementation-devcontentops-workflow.rst](https://github.com/craftercms/docs/blob/master/source/new-ia/by-role/developer/developer-workflow/implementation-devcontentops-workflow.rst)
- [ ] [by-role/developer/developer-workflow/implementation-prod-repo-sync.rst](https://github.com/craftercms/docs/blob/master/source/new-ia/by-role/developer/developer-workflow/implementation-prod-repo-sync.rst)
- [ ] (Vita) [by-role/system-admin/studio/create-project-with-link-to-remote-repo.rst](https://github.com/craftercms/docs/blob/master/source/new-ia/by-role/system-admin/studio/create-project-with-link-to-remote-repo.rst)
