### ISSUE TITLE
Update Publish/Review dialogs

### ISSUE THREAD

**Issue by sumerjabri** [craftersoftware/craftercms#6864]
### Latest version

- [X] The issue is in the develop branch
- [ ] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

The APIs are changing, the dialogs won't work with the new APIs.
The current dialogs show a list of files, which is hard to visualize. They also require the user to click a button to see the dependencies.

- [ ] Publishing Dialog (Publish, Approve, Request)
- [ ] Dashboard/Dashlets
- [ ] Publishing queue widget
- [ ] Publish on demand widget
- [ ] Git tools, _pull_ from remote may cancel packages and we must warn the user and get approval or cancel

### Describe the solution you'd like

Switch to the new APIs, and note the 4 categories returned: items, deleted, hard deps, soft deps.

The returned items are no longer just a list of files, but now have more metadata. Update the dialogs to leverage the new metadata to show a rich interface with more information to the publisher/reviewer.

### Tasks
- [ ] Design dialog 1
- [ ] Implement dialog 1

**Comment by rart** [comment]
We've abstained from having a bulk DetailedItem retrieval service since that's a more expensive Item to create; however, all along, the Publishing Dialog has needed and indeed used the `live` & `sandbox` data and it does individual `item_by_path` requests to retrieve them.

As it stands, the DetailedItem is used to retrieve the `dateScheduled` property and show the right publishing date when the packages is set to be published at a later date/time.

We should either create this bulk service, or discuss taking down the level of information the Publishing Dialog manages to avoid these requests as individual requests. This relates to the dependency services too.

**Comment by sumerjabri** [comment]
Related to https://github.com/craftercms/craftercms/issues/7542
